---
name: Codebase Style - Web
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    paths:
      - "ReconnectED-web/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint-web:
    name: Lint - Web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    defaults:
      run:
        working-directory: ${{ github.workspace }}/ReconnectED-web

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2 # zizmor: ignore[unpinned-uses]

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        working-directory: ./ReconnectED-web
        run: bun run lint
