---
name: Codebase Style - Android
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    paths:
      - "ReconnectED-Android/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint-android:
    name: Lint - Android
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    defaults:
      run:
        working-directory: ${{ github.workspace }}/ReconnectED-web

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.7.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

      - name: Run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true

      - name: Annotate From ktlint Report
        uses: yutailang0119/action-ktlint@v4
        with:
          report-path: build/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
          ignore-warnings: true
        continue-on-error: false
